# fly.toml app configuration file generated for rkm-service-manager-api on 2026-08-20T14:10:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rkm-service-manager'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/rkm.db'
  DB_IMPORT_PATH = '/data/rkm-import.sqlite'

[mounts]
  source = 'rkm_data'
  destination = '/data'

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
